[package]
name = "pihole_api"
version = "0.1.0"
authors = ["Mcat12 <mark@pi-hole.net>"]
description = "Work in progress HTTP API for Pi-hole."
homepage = "https://pi-hole.net"
repository = "https://github.com/pi-hole/api"
readme = "README.md"
license = "EUPL-1.2"
publish = false

[profile.release]
lto = true

[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket", branch = "v0.3" }
rocket_codegen = { git = "https://github.com/SergioBenitez/Rocket", branch = "v0.3" }
rocket_contrib = { git = "https://github.com/SergioBenitez/Rocket", branch = "v0.3" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
rmp = "0.8"
regex = "0.2"

[patch.crates-io]
ring = { git = "https://github.com/SergioBenitez/ring", branch = "v0.11" }
