version: 2

.job_template: &job_template
  docker:
    - image: thepihole/api-build:$CIRCLE_JOB
  steps:
    - checkout
    - restore_cache:
        keys:
          # Find a cache corresponding to this specific Cargo.toml checksum and target.
          # When the target is different, this key will fail
          - v2-cargo-{{ .Branch }}-{{ checksum "Cargo.toml" }}-{{ .Environment.CIRCLE_JOB }}
          # Find a cache corresponding to this specific Cargo.toml checksum.
          # When this file is changed, this key will fail.
          - v2-cargo-{{ .Branch }}-{{ checksum "Cargo.toml" }}
          # Find a cache corresponding to any build in this branch, regardless of Cargo.toml checksum.
          # The most recent one will be used.
          - v2-cargo-{{ .Branch }}
          # Find the most recent cache used from any branch
          - v2-cargo
    - run:
        name: "Build"
        command: |
          time cargo build --release --target $TARGET
          cp target/$TARGET/release/pihole_api ${BIN_NAME}
    - run:
        name: "Test"
        command: |
          [[ "$CIRCLE_JOB" != "x86_64" ]] || time cargo test --release --target $TARGET
    - run:
        name: "Upload"
        command: |
          sha1sum ${BIN_NAME} > ${BIN_NAME}.sha1
          cat ${BIN_NAME}.sha1
          curl https://ftl.pi-hole.net:8080/FTL-client -o FTL-client
          chmod +x ./FTL-client
          [[ "$CIRCLE_PR_NUMBER" == "" ]] && ./FTL-client "${CIRCLE_BRANCH}" "${BIN_NAME}" "${FTL_SECRET}"
          [[ "$CIRCLE_PR_NUMBER" == "" ]] && ./FTL-client "${CIRCLE_BRANCH}" "${BIN_NAME}.sha1" "${FTL_SECRET}"
          rm ./FTL-client
    - save_cache:
        key: v2-cargo-{{ .Branch }}-{{ checksum "Cargo.toml" }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Cargo.lock" }}
        paths:
          - target

jobs:
  arm:
    <<: *job_template
    environment:
      BIN_NAME: "pihole-API-arm-linux-gnueabi"
      TARGET: "arm-unknown-linux-gnueabi"

  armhf:
    <<: *job_template
    environment:
      BIN_NAME: "pihole-API-arm-linux-gnueabihf"
      TARGET: "arm-unknown-linux-gnueabihf"

  aarch64:
    <<: *job_template
    environment:
      BIN_NAME: "pihole-API-aarch64-linux-gnu"
      TARGET: "aarch64-unknown-linux-gnu"

  x86_64:
    <<: *job_template
    environment:
      BIN_NAME: "pihole-API-linux-x86_64"
      TARGET: "x86_64-unknown-linux-gnu"
      SKIP_ADDING_TARGET: "1" # We're already running on x86_64

  x86_64-musl:
    <<: *job_template
    environment:
      BIN_NAME: "pihole-API-musl-linux-x86_64"
      TARGET: "x86_64-unknown-linux-musl"

  x86_32:
    <<: *job_template
    environment:
      BIN_NAME: "pihole-API-linux-x86_32"
      TARGET: "i686-unknown-linux-gnu"

workflows:
  version: 2
  build:
    jobs:
      - arm
      - armhf
      - aarch64
      - x86_64
      - x86_64-musl
      - x86_32
